import type { Metadata } from "next";
import {
  // Poppins,
  Averia_Sans_Libre
} from "next/font/google";
import "./globals.css";

// import RootLayoutCustom from "@/component/RootLayer/RootLayout";
import { AuthProvider } from "../context/AuthContext";
import { CowRegistrationProvider } from "@/context/CowRegistrationContext";
import { FarmerRegistrationProvider } from "@/context/FarmerRegistrationContext";
import { InsuranceApplicationProvider } from "@/context/InsuranceApplicationContext";



const averia = Averia_Sans_Libre({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${averia.className}  antialiased`}
      >
        <AuthProvider>
        <InsuranceApplicationProvider>
          <FarmerRegistrationProvider>         
             <CowRegistrationProvider>
            {/* <RootLayoutCustom> */}
            {children}
          </CowRegistrationProvider>
          </FarmerRegistrationProvider>
          </InsuranceApplicationProvider>

          {/* </RootLayoutCustom> */}
        </AuthProvider>


      </body>
    </html>
  );
}
